### ISSUE TITLE
ngrok 사용법 (macOS)

### ISSUE THREAD

**Issue by caboooom** [caboom-log/study-log#9]
1. 설치
```bash
brew install ngrok/ngrok/ngrok
```

2-1 . authKey 등록 후 백그라운드로 특정 포트 열기
```bash
ngrok config add-authtoken 토큰
nohup ngrok tcp 1234 &
```

2-2. ngrok.yml 파일 작성 후 백그라운드로 모두 실행하기
```yaml
# ngrok.yml
version: "3"
agent:
    authtoken: 토큰
tunnels:
  mysql:
    proto: tcp
    addr: 1234
  redis:
    proto: tcp
    addr: 5678
```

```bash
ngrok start --all --config ngrok.yml > /dev/null &
```

3. 접속 정보 확인
```bash
curl http://localhost:4040/api/tunnels
```
